<?php
namespace Ishep\Services;
use PDO;use Throwable;use DomainException;use Ishep\Repositories\{MembershipApplicationRepository,MembershipTypeRepository,MemberProfileRepository,AuditLogRepository,RoleRepository};
final class MembershipApplicationService
{
 public function __construct(private PDO $db,private MembershipApplicationRepository $applications,private MembershipTypeRepository $types,private MemberProfileRepository $profiles,private ProfileCompletionService $completion,private AuditLogRepository $audits,private RoleRepository $roles,private MembershipApplicationStatus $statuses,private ?FinanceService $finance=null){}
 private function transaction(callable $work):mixed{$this->db->beginTransaction();try{$result=$work();$this->db->commit();return$result;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 private function number():string{return'ISH-APP-'.gmdate('Y').'-'.strtoupper(bin2hex(random_bytes(8)));}
 private function member(int $uid):void{if(!in_array('registered_user',$this->roles->roles($uid),true)||!in_array('membership.apply',$this->roles->permissions($uid),true))throw new DomainException('Your account is not authorized to apply.');}
 private function type(int $id):void{if(!$this->types->activeById($id))throw new DomainException('Select a valid active membership type.');}
 public function saveDraft(int $uid,int $type,string $ip):array{$this->member($uid);$this->type($type);return$this->transaction(function()use($uid,$type,$ip){$latest=$this->applications->latestForUser($uid);if($latest&&$latest['status']==='rejected'){$this->statuses->assert('rejected','draft');$this->applications->transition((int)$latest['id'],'draft',$uid);$this->applications->event((int)$latest['id'],$uid,'rejected','draft','Applicant opened the application for correction.');$id=(int)$latest['id'];}elseif($latest&&$latest['status']==='draft')$id=(int)$latest['id'];elseif($latest&&$latest['status']!=='withdrawn')throw new DomainException('An active application already exists.');else{$id=$this->applications->create($uid,$type,$this->number());$this->applications->event($id,$uid,null,'draft','Application draft created.');}$this->applications->updateDraft($id,$type);$this->audits->record($uid,'membership_application.draft_saved','membership_application',$id,$ip);return$this->applications->latestForUser($uid);});}
 public function submit(int $uid,bool $declared,string $ip):array{$this->member($uid);$app=$this->applications->latestForUser($uid);if(!$app)throw new DomainException('Create an application draft first.');$this->statuses->assert($app['status'],'submitted');$this->type((int)$app['membership_type_id']);$result=$this->completion->calculate($this->profiles->byUserId($uid)??[]);if(!$result['complete'])throw new DomainException('Complete your profile before submitting: '.implode(', ',array_values($result['missing'])).'.');if(!$declared)throw new DomainException('You must accept the applicant declaration.');return$this->change($app,$uid,'submitted','Application submitted by the member.',null,null,$ip);}
 public function withdraw(int $uid,string $ip):array{$this->member($uid);$app=$this->applications->latestForUser($uid);if(!$app)throw new DomainException('No application was found.');return$this->change($app,$uid,'withdrawn','Application withdrawn by the member.',null,null,$ip);}
 public function review(string $number,int $reviewer,string $action,?string $reason,?string $internal,string $ip):array{$this->reviewer($reviewer);$app=$this->applications->byNumber($number);if(!$app)throw new DomainException('Application not found.');$target=['start-review'=>'under_review','approve'=>'approved','reject'=>'rejected'][$action]??'';if(!$target)throw new DomainException('Invalid review action.');$reason=trim((string)$reason);$internal=trim((string)$internal);if($target==='rejected'&&$reason==='')throw new DomainException('A meaningful applicant-visible rejection reason is required.');if(mb_strlen($reason)>1000||mb_strlen($internal)>2000)throw new DomainException('Review notes exceed the allowed length.');return$this->change($app,$reviewer,$target,$target==='rejected'?$reason:'Application moved to '.$this->statuses->label($target).'.',$reason?:null,$internal?:null,$ip);}
 private function reviewer(int $uid):void{$roles=$this->roles->roles($uid);if(!array_intersect($roles,['administrator','super_user']))throw new DomainException('You are not authorized to review applications.');}
 private function change(array $app,int $actor,string $to,?string $eventNote,?string $reason,?string $internal,string $ip):array{$this->statuses->assert($app['status'],$to);return$this->transaction(function()use($app,$actor,$to,$eventNote,$reason,$internal,$ip){$id=(int)$app['id'];$this->applications->transition($id,$to,$actor,$reason,$internal);$this->applications->event($id,$actor,$app['status'],$to,$eventNote);$this->audits->record($actor,'membership_application.'.$to,'membership_application',$id,$ip);$updated=$this->applications->byNumber($app['application_number']);if($to==='approved'&&$this->finance)$this->finance->provisionApproved($updated,$actor,$ip);return$updated;});}
}
