<?php
namespace Ishep\Services;
use DomainException;use PDO;use Throwable;use Ishep\Repositories\AuditLogRepository;use Ishep\Security\PasswordPolicy;
final class UserAdministrationService
{
 public const ROLES=['registered_user','administrator','finance','super_user'];public const STAFF_ROLES=['administrator','finance','super_user'];public const STATUSES=['active','suspended'];
 public function __construct(private PDO $db,private AuditLogRepository $audits,private PasswordPolicy $policy=new PasswordPolicy()){}
 private function email(string $email):string{$email=strtolower(trim($email));if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new DomainException('A valid email address is required.');return$email;}
 private function tx(callable $fn):mixed{$this->db->beginTransaction();try{$value=$fn();$this->db->commit();return$value;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 private function user(string $email):array{$s=$this->db->prepare('SELECT id,email,account_status FROM users WHERE email=?');$s->execute([$this->email($email)]);return$s->fetch()?:throw new DomainException('User not found.');}
 private function role(string $role):int{if(!in_array($role,self::ROLES,true))throw new DomainException('Invalid role. Allowed: '.implode(', ',self::ROLES));$s=$this->db->prepare('SELECT id FROM roles WHERE code=?');$s->execute([$role]);return(int)($s->fetchColumn()?:throw new DomainException('Configured role not found.'));}
 public function create(string $name,string $email,string $password,int $membershipTypeId):int{$name=trim($name);$email=$this->email($email);if($name===''||mb_strlen($name)>255)throw new DomainException('Name is required and must not exceed 255 characters.');$errors=$this->policy->errors($password);if($errors)throw new DomainException(implode(' ',$errors));return$this->tx(function()use($name,$email,$password,$membershipTypeId){$type=$this->db->prepare('SELECT id FROM membership_types WHERE id=? AND active=1');$type->execute([$membershipTypeId]);if(!$type->fetchColumn())throw new DomainException('Select a valid active membership type.');$s=$this->db->prepare("INSERT INTO users(name,email,password,membership_type_id,account_status,created_at,updated_at)VALUES(?,?,?,?,'active',UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT),$membershipTypeId]);$id=(int)$this->db->lastInsertId();$role=$this->role('registered_user');$this->db->prepare('INSERT INTO user_roles(user_id,role_id,assigned_by,assigned_at)VALUES(?,?,NULL,UTC_TIMESTAMP())')->execute([$id,$role]);$this->audits->record(null,'cli.user_created','user',$id,'cli');return$id;});}
 public function createStaff(string $name,string $email,string $role,string $password,bool $dryRun=false):int{ $name=trim($name);$email=$this->email($email);if($name===''||mb_strlen($name)>255)throw new DomainException('Name is required and must not exceed 255 characters.');if(!in_array($role,self::STAFF_ROLES,true))throw new DomainException('Invalid staff role. Allowed: '.implode(', ',self::STAFF_ROLES));$errors=$this->policy->errors($password);if($errors)throw new DomainException(implode(' ',$errors));$roleId=$this->role($role);$existing=$this->db->prepare('SELECT id FROM users WHERE email=?');$existing->execute([$email]);if($existing->fetchColumn())throw new DomainException('An account already uses this email.');if($dryRun)return 0;return$this->tx(function()use($name,$email,$password,$roleId,$role){$s=$this->db->prepare("INSERT INTO users(name,email,password,membership_type_id,account_status,created_at,updated_at)VALUES(?,?,?,NULL,'active',UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT)]);$id=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO user_roles(user_id,role_id,assigned_by,assigned_at)VALUES(?,?,NULL,UTC_TIMESTAMP())')->execute([$id,$roleId]);$this->audits->record(null,'cli.staff_user_created.'.$role,'user',$id,'cli');return$id;});}
 public function listUsers(?string $email=null):array{$sql="SELECT u.id,u.name,u.email,u.account_status,u.membership_type_id,mt.name AS membership_type_name,GROUP_CONCAT(r.code ORDER BY r.code SEPARATOR ', ') AS roles FROM users u LEFT JOIN membership_types mt ON mt.id=u.membership_type_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id";$params=[];if($email!==null){$sql.=' WHERE u.email=?';$params[]=$this->email($email);}$sql.=' GROUP BY u.id,u.name,u.email,u.account_status,u.membership_type_id,mt.name ORDER BY u.email';$s=$this->db->prepare($sql);$s->execute($params);return$s->fetchAll();}
 public function removeTestUser(string $email,bool $apply=false,bool $confirmNonTest=false):array{$user=$this->listUsers($email)[0]??throw new DomainException('User not found.');$isTest=str_ends_with($user['email'],'@example.test')&&preg_match('/\btest\b/i',$user['name']);if(!$isTest&&!$confirmNonTest)throw new DomainException('Refusing to remove an unmarked account. Use --confirm-non-test only after deliberate review.');$roles=array_filter(array_map('trim',explode(', ',(string)$user['roles'])));if(in_array('super_user',$roles,true)){$count=(int)$this->db->query("SELECT COUNT(DISTINCT ur.user_id) FROM user_roles ur JOIN roles r ON r.id=ur.role_id JOIN users u ON u.id=ur.user_id WHERE r.code='super_user' AND u.account_status='active'")->fetchColumn();if($count<=1)throw new DomainException('Cannot remove the final active super-user.');}if($apply)$this->tx(function()use($user){$this->db->prepare('DELETE FROM users WHERE id=?')->execute([(int)$user['id']]);$this->audits->record(null,'cli.test_user_removed','user',(int)$user['id'],'cli');});return$user;}
 public function assign(string $email,string $role):void{$user=$this->user($email);$roleId=$this->role($role);$this->tx(function()use($user,$role,$roleId){$s=$this->db->prepare('INSERT IGNORE INTO user_roles(user_id,role_id,assigned_by,assigned_at)VALUES(?,?,NULL,UTC_TIMESTAMP())');$s->execute([(int)$user['id'],$roleId]);$this->audits->record(null,'cli.role_assigned.'.$role,'user',(int)$user['id'],'cli');});}
 public function remove(string $email,string $role):void{$user=$this->user($email);$roleId=$this->role($role);if($role==='super_user'){$count=(int)$this->db->query("SELECT COUNT(DISTINCT ur.user_id) FROM user_roles ur JOIN roles r ON r.id=ur.role_id JOIN users u ON u.id=ur.user_id WHERE r.code='super_user' AND u.account_status='active'")->fetchColumn();if($count<=1)throw new DomainException('Cannot remove the final active super-user.');}$this->tx(function()use($user,$role,$roleId){$this->db->prepare('DELETE FROM user_roles WHERE user_id=? AND role_id=?')->execute([(int)$user['id'],$roleId]);$this->audits->record(null,'cli.role_removed.'.$role,'user',(int)$user['id'],'cli');});}
 public function roles(string $email):array{$user=$this->user($email);$s=$this->db->prepare('SELECT r.code FROM roles r JOIN user_roles ur ON ur.role_id=r.id WHERE ur.user_id=? ORDER BY r.code');$s->execute([(int)$user['id']]);return array_column($s->fetchAll(),'code');}
 public function status(string $email,string $status):void{if(!in_array($status,self::STATUSES,true))throw new DomainException('Status must be active or suspended.');$user=$this->user($email);if($status==='suspended'&&in_array('super_user',$this->roles($email),true)){$count=(int)$this->db->query("SELECT COUNT(DISTINCT ur.user_id) FROM user_roles ur JOIN roles r ON r.id=ur.role_id JOIN users u ON u.id=ur.user_id WHERE r.code='super_user' AND u.account_status='active'")->fetchColumn();if($count<=1)throw new DomainException('Cannot suspend the final active super-user.');}$this->tx(function()use($user,$status){$this->db->prepare('UPDATE users SET account_status=?,remember_token=NULL,updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([$status,(int)$user['id']]);$this->audits->record(null,'cli.account_'.$status,'user',(int)$user['id'],'cli');});}
}
