<?php $selected=static fn(string $key,mixed $default=''):string=>old($key,(string)($profile[$key]??$default));?>
<div class="row justify-content-center"><div class="col-xl-9">
<div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h2 mb-0">Edit your profile</h1><a class="btn btn-outline-secondary" href="<?=e(url('/profile'))?>">Cancel</a></div>
<form method="post" action="<?=e(url('/profile'))?>" class="card shadow-sm"><div class="card-body p-4"><?=csrf_field()?><div class="row g-3">
<?php $textFields=['name'=>['Full name',255,true],'telephone'=>['Telephone / mobile',30,true],'organisation'=>['Organisation / employer',255,false],'job_title'=>['Job title',255,false]];foreach($textFields as $key=>[$label,$max,$required]):?>
<div class="col-md-6"><label class="form-label" for="<?=e($key)?>"><?=e($label)?><?=$required?'':' (optional)'?></label><input class="form-control" id="<?=e($key)?>" name="<?=e($key)?>" maxlength="<?=e($max)?>" <?=$required?'required':''?> value="<?=e($selected($key))?>"><?php if(field_errors($key)):?><div class="invalid-feedback d-block"><?=e(implode(' ',field_errors($key)))?></div><?php endif;?></div><?php endforeach;?>
<div class="col-md-6"><label class="form-label" for="email">Account email</label><input class="form-control" id="email" type="email" readonly value="<?=e($profile['email']??'')?>"><div class="form-text">Email changes are outside this profile workflow.</div></div>
<?php foreach(['membership_type_id'=>['Membership type',$membershipTypes],'province_id'=>['Province',$provinces],'profession_id'=>['Profession',$professions]] as $key=>[$label,$items]):?><div class="col-md-6"><label class="form-label" for="<?=e($key)?>"><?=e($label)?></label><select class="form-select" id="<?=e($key)?>" name="<?=e($key)?>" required><option value="">Select <?=e(strtolower($label))?></option><?php foreach($items as $item):?><option value="<?=e($item['id'])?>" <?=$selected($key)===(string)$item['id']?'selected':''?>><?=e($item['name'])?></option><?php endforeach;?></select><?php if(field_errors($key)):?><div class="invalid-feedback d-block"><?=e(implode(' ',field_errors($key)))?></div><?php endif;?></div><?php endforeach;?>
<div class="col-12"><label class="form-label" for="biography">Short professional biography (optional)</label><textarea class="form-control" id="biography" name="biography" maxlength="1000" rows="5"><?=e($selected('biography'))?></textarea></div>
</div></div><div class="card-footer bg-white p-4 text-end"><button class="btn btn-primary" type="submit">Save Profile</button></div></form></div></div>
