<?php
declare(strict_types=1);
$base=dirname(__DIR__);$autoload=$base.'/vendor/autoload.php';if(is_file($autoload))require$autoload;else{spl_autoload_register(static function(string $class)use($base):void{$p='Ishep\\';if(str_starts_with($class,$p)){$f=$base.'/src/'.str_replace('\\','/',substr($class,strlen($p))).'.php';if(is_file($f))require$f;}});require$base.'/src/Support/helpers.php';}
use Ishep\Http\{Request,Response};use Ishep\Routing\Router;use Ishep\Validation\Validator;
use Ishep\Config\Environment;use Ishep\Database\ConnectionFactory;use Ishep\Repositories\{UserRepository,RoleRepository,MembershipTypeRepository,MemberProfileRepository,ReferenceRepository,AuditLogRepository};use Ishep\Services\{RegistrationService,AuthenticationService,RateLimiter,MemberProfileService,ProfileCompletionService};use Ishep\Validation\MemberProfileValidator;use Ishep\Security\{PasswordPolicy,Session};
$tests=0;$failures=[];$check=function(bool $ok,string $name)use(&$tests,&$failures){$tests++;if(!$ok)$failures[]=$name;};
$check(e('<script>')==='&lt;script&gt;','HTML escaping');
$v=(new Validator())->validate(['email'=>'bad','password'=>'short','password_confirmation'=>'other','terms'=>'0'],['email'=>['email'],'password'=>['min:8','confirmed'],'terms'=>['accepted']]);$check(isset($v['email'],$v['password'],$v['terms']),'validation rules');
$router=new Router();$router->get('/hello/{name}',fn($r)=>new Response('Hello '.$r->get('name')));$response=$router->dispatch(new Request('GET','/hello/Ada',[],[],[]));$check($response->status===200&&$response->body==='Hello Ada','route parameters');$check($router->dispatch(new Request('POST','/hello/Ada',[],[],[]))->status===405,'405 handling');$check($router->dispatch(new Request('GET','/missing',[],[],[]))->status===404,'404 handling');
$required=['/','/membership','/careers','/bursaries','/verify-membership','/health','/register','/login','/logout','/forgot-password','/reset-password/{token}','/reset-password','/dashboard','/profile','/profile/edit','/dashboard/administrator','/dashboard/finance','/dashboard/super-user'];$index=(string)file_get_contents($base.'/public/index.php');foreach($required as$route)$check(str_contains($index,"'".$route."'"),'route '.$route);
$check(substr_count($index,"'/profile'")>=2&&str_contains($index,'array_merge([$csrf],$protected)'),'profile routes require authentication and CSRF on update');
$check(!str_contains((string)file_get_contents($base.'/src/Http/Controllers/ProfileController.php'),"input['user_id']"),'profile ownership uses authenticated session user');
$completion=new ProfileCompletionService();$check($completion->calculate([])['percent']===0,'missing profile completion is zero');$check($completion->calculate(['name'=>'A','email'=>'a@b.test','membership_type_id'=>1,'telephone'=>'1','province_id'=>1,'profession_id'=>1])['percent']===100,'complete profile completion is 100');
$check(!str_contains((string)file_get_contents($base.'/templates/pages/profile/show.php'),'password'),'profile display excludes authentication secrets');
$check(str_contains((string)file_get_contents($base.'/templates/pages/dashboards/member.php'),'Profile completion'),'dashboard displays profile completion');
$example=(string)file_get_contents($base.'/.env.example');$sql=(string)file_get_contents($base.'/database/install.sql');$sqlStatements=(string)preg_replace('/--.*$/m','',$sql);
$check(str_contains($example,'DB_DATABASE=ishep_crm'),'example database name');
$check((bool)preg_match('/\bUSE\s+`ishep_crm`\s*;/i',$sql),'installer target database');
$legacyDatabase='ishep_crm'.'_personal';$check(!str_contains(strtolower($sql),$legacyDatabase),'legacy database name absent');
$check(!preg_match('/\b(DROP\s+DATABASE|CREATE\s+DATABASE|DROP\s+TABLE|TRUNCATE\s+(?:TABLE\s+)?)/i',$sqlStatements),'installer has no destructive database statements');
$policy=new PasswordPolicy();$check(count($policy->errors('weak'))===3,'weak password rejected consistently');$check($policy->errors('StrongPass1')===[],'strong password accepted consistently');
$authScript=(string)file_get_contents($base.'/public/assets/js/auth-password.js');$registerTemplate=(string)file_get_contents($base.'/templates/pages/auth/register.php');
$check(str_contains($authScript,'data-password-rule')&&str_contains($authScript,"aria-pressed"),'password checklist and toggle script present');
$check(str_contains($authScript,'Passwords match.')&&str_contains($authScript,'Passwords do not match.'),'password confirmation feedback present');
$check(str_contains($registerTemplate,'data-password-form')&&str_contains($registerTemplate,'data-password-overall'),'registration password feedback markup present');
$limiter=new RateLimiter($base.'/storage/sessions');$limitKey='automated-rate-limit-'.bin2hex(random_bytes(4));for($attempt=0;$attempt<5;$attempt++)$limiter->hit($limitKey);$check($limiter->blocked($limitKey),'login throttling activates after five attempts');$limiter->clear($limitKey);
Environment::load($base.'/.env');
try{$pdo=ConnectionFactory::make(require$base.'/config/database.php');$users=new UserRepository($pdo);$roles=new RoleRepository($pdo);$memberships=new MembershipTypeRepository($pdo);$type=$memberships->active()[0]??null;$testEmail='codex.php.tests@example.test';$rollbackEmail='codex.rollback.tests@example.test';$cleanup=$pdo->prepare('DELETE FROM users WHERE email IN (?,?)');$cleanup->execute([$testEmail,$rollbackEmail]);
if($type){$check($memberships->activeById(PHP_INT_MAX)===null,'invalid membership type rejected');$service=new RegistrationService($pdo,$users,$roles);$id=$service->register('Codex PHP Test',$testEmail,'StrongPass1',(int)$type['id']);$created=$users->byId($id);$check($created!==null,'valid registration creates user');$check(password_verify('StrongPass1',$created['password']),'registered password is hashed');$check($roles->roles($id)===['registered_user'],'only registered_user assigned');try{$service->register('Duplicate',$testEmail,'StrongPass1',(int)$type['id']);$check(false,'duplicate email rejected');}catch(Throwable){$check($users->byEmail($testEmail)!==null,'duplicate email rejected');}$throwingRoles=new class($pdo) extends RoleRepository{public function assignRegistered(int $userId):void{throw new RuntimeException('simulated role failure');}};try{(new RegistrationService($pdo,$users,$throwingRoles))->register('Rollback Test',$rollbackEmail,'StrongPass1',(int)$type['id']);$check(false,'role failure rolls back');}catch(Throwable){$check($users->byEmail($rollbackEmail)===null,'role failure rolls back');}$session=new Session();$session->start('ishep_cli_test',5,$base.'/storage/sessions');$authentication=new AuthenticationService($users,$session);$status=$pdo->prepare('UPDATE users SET account_status=? WHERE id=?');$status->execute(['suspended',$id]);$check(!$authentication->attempt($testEmail,'StrongPass1'),'inactive account cannot authenticate');$status->execute(['active',$id]);$check($authentication->attempt($testEmail,'StrongPass1'),'login succeeds with valid password');$authentication->logout();$check($session->get('user_id')===null,'logout invalidates authentication session');}else{$check(false,'active membership type available');}
// Profile integration uses only disposable records and verifies transaction rollback.
if(isset($id,$type)){$provinceId=(int)$pdo->query('SELECT id FROM provinces WHERE active=1 ORDER BY id LIMIT 1')->fetchColumn();$professionName='Codex Disposable Profession';$pdo->prepare('INSERT INTO professions (name,active,created_at,updated_at) VALUES (?,1,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute([$professionName]);$professionId=(int)$pdo->lastInsertId();$profiles=new MemberProfileRepository($pdo);$references=new ReferenceRepository($pdo);$profileService=new MemberProfileService($pdo,$users,$profiles,new AuditLogRepository($pdo));$validator=new MemberProfileValidator($memberships,$references);$valid=['name'=>'Codex Profile Test','telephone'=>'+27 82 000 0000','membership_type_id'=>(int)$type['id'],'province_id'=>$provinceId,'profession_id'=>$professionId,'organisation'=>'ISHEP Test','job_title'=>'Tester','biography'=>'<script>alert(1)</script>'];[$profileData,$profileErrors]=$validator->validate($valid);$check($profileErrors===[],'valid profile accepted');$profileId=$profileService->update($id,$profileData,'127.0.0.1');$stored=$profiles->byUserId($id);$check($profileId>0&&$stored['telephone']===$valid['telephone'],'profile creation succeeds');$valid['telephone']='+27 82 111 1111';[$profileData]=$validator->validate($valid);$profileService->update($id,$profileData,'127.0.0.1');$check($profiles->byUserId($id)['telephone']===$valid['telephone'],'profile update succeeds');foreach(['province_id','profession_id','membership_type_id'] as $field){$invalid=$valid;$invalid[$field]=PHP_INT_MAX;[, $invalidErrors]=$validator->validate($invalid);$check(isset($invalidErrors[$field]),'invalid '.$field.' rejected');}$tooLong=$valid;$tooLong['organisation']=str_repeat('x',256);[, $lengthErrors]=$validator->validate($tooLong);$check(isset($lengthErrors['organisation']),'profile maximum lengths enforced');$check(e($stored['biography'])==='&lt;script&gt;alert(1)&lt;/script&gt;','profile output escaping');$beforeName=$users->byId($id)['name'];$rollback=$profileData;$rollback['name']='Must Roll Back';$rollback['province_id']=PHP_INT_MAX;try{$profileService->update($id,$rollback,'127.0.0.1');$check(false,'profile transaction failure raised');}catch(Throwable){$check($users->byId($id)['name']===$beforeName,'profile transaction rolls back');}$rolesBefore=$roles->roles($id);$statusBefore=$users->byId($id)['account_status'];$ignored=$valid+['role'=>'administrator','account_status'=>'suspended','user_id'=>$id+1];[$safeData]=$validator->validate($ignored);$profileService->update($id,$safeData,'127.0.0.1');$check($roles->roles($id)===$rolesBefore,'member cannot change roles');$check($users->byId($id)['account_status']===$statusBefore,'member cannot change account status');$check($profiles->byUserId($id+1)===null,'profile ownership enforced');$pdo->prepare('DELETE FROM professions WHERE id=?')->execute([$professionId]);}
}catch(Throwable $exception){$failures[]='database integration: '.get_class($exception);}finally{if(isset($cleanup))$cleanup->execute([$testEmail,$rollbackEmail]);if(isset($pdo,$professionId))$pdo->prepare('DELETE FROM professions WHERE id=?')->execute([$professionId]);}
if($failures){fwrite(STDERR,"FAIL (".count($failures)."/{$tests})\n - ".implode("\n - ",$failures)."\n");exit(1);}echo"PASS {$tests} checks\n";
