<?php
namespace Ishep\Bootstrap;
use PDO;use Ishep\Config\Environment;use Ishep\Database\ConnectionFactory;use Ishep\Security\{Session,Csrf};use Ishep\Support\Logger;use Ishep\Repositories\{UserRepository,RoleRepository,PasswordResetRepository,AuditLogRepository,MembershipTypeRepository,MemberProfileRepository,ReferenceRepository,MembershipApplicationRepository,MemberDocumentRepository,FinanceRepository};use Ishep\Services\{AuthenticationService,AuthorizationService,RateLimiter,RegistrationService,PasswordResetService,MemberProfileService,ProfileCompletionService,MembershipApplicationService,MembershipApplicationStatus,MemberDocumentService,PrivateDocumentStorage,DocumentStatus,FinanceService};
final class Application
{
    private static self $instance; private array $config=[]; private ?PDO $db=null; private Session $session; private Csrf $csrf; private Logger $logger; private array $services=[];
    public function __construct(private string $base){self::$instance=$this;Environment::load($base.'/.env');$this->config=['app'=>require$base.'/config/app.php','database'=>require$base.'/config/database.php','documents'=>require$base.'/config/documents.php'];date_default_timezone_set($this->config['app']['timezone']);$this->session=new Session();$this->session->start($this->config['app']['session']['name'],$this->config['app']['session']['lifetime'],$base.'/storage/sessions');$this->session->ageFlash();$this->csrf=new Csrf($this->session);$this->logger=new Logger($base.'/storage/logs/app.log');}
    public static function instance():self{return self::$instance;} public function config(string $key,mixed $default=null):mixed{$x=$this->config;foreach(explode('.',$key)as$p){if(!is_array($x)||!array_key_exists($p,$x))return$default;$x=$x[$p];}return$x;} public function session():Session{return$this->session;} public function csrf():Csrf{return$this->csrf;} public function logger():Logger{return$this->logger;}
    public function db():PDO{return$this->db??=ConnectionFactory::make($this->config['database']);} private function one(string $key,callable $make):mixed{return$this->services[$key]??=$make();}
    public function users():UserRepository{return$this->one(__FUNCTION__,fn()=>new UserRepository($this->db()));} public function roles():RoleRepository{return$this->one(__FUNCTION__,fn()=>new RoleRepository($this->db()));} public function memberships():MembershipTypeRepository{return$this->one(__FUNCTION__,fn()=>new MembershipTypeRepository($this->db()));} public function resets():PasswordResetRepository{return$this->one(__FUNCTION__,fn()=>new PasswordResetRepository($this->db()));} public function audits():AuditLogRepository{return$this->one(__FUNCTION__,fn()=>new AuditLogRepository($this->db()));} public function profiles():MemberProfileRepository{return$this->one(__FUNCTION__,fn()=>new MemberProfileRepository($this->db()));} public function references():ReferenceRepository{return$this->one(__FUNCTION__,fn()=>new ReferenceRepository($this->db()));} public function applications():MembershipApplicationRepository{return$this->one(__FUNCTION__,fn()=>new MembershipApplicationRepository($this->db()));} public function documents():MemberDocumentRepository{return$this->one(__FUNCTION__,fn()=>new MemberDocumentRepository($this->db()));} public function finance():FinanceRepository{return$this->one(__FUNCTION__,fn()=>new FinanceRepository($this->db()));}
    public function auth():AuthenticationService{return$this->one(__FUNCTION__,fn()=>new AuthenticationService($this->users(),$this->session));} public function authorization():AuthorizationService{return$this->one(__FUNCTION__,fn()=>new AuthorizationService($this->roles()));} public function registration():RegistrationService{return$this->one(__FUNCTION__,fn()=>new RegistrationService($this->db(),$this->users(),$this->roles()));} public function passwordReset():PasswordResetService{return$this->one(__FUNCTION__,fn()=>new PasswordResetService($this->db(),$this->users(),$this->resets(),$this->logger,$this->config['app']['mail']));} public function limiter():RateLimiter{return$this->one(__FUNCTION__,fn()=>new RateLimiter($this->base.'/storage/sessions'));} public function profileService():MemberProfileService{return$this->one(__FUNCTION__,fn()=>new MemberProfileService($this->db(),$this->users(),$this->profiles(),$this->audits()));} public function profileCompletion():ProfileCompletionService{return$this->one(__FUNCTION__,fn()=>new ProfileCompletionService());}
    public function applicationStatuses():MembershipApplicationStatus{return$this->one(__FUNCTION__,fn()=>new MembershipApplicationStatus());} public function applicationService():MembershipApplicationService{return$this->one(__FUNCTION__,fn()=>new MembershipApplicationService($this->db(),$this->applications(),$this->memberships(),$this->profiles(),$this->profileCompletion(),$this->audits(),$this->roles(),$this->applicationStatuses(),$this->financeService()));} public function financeService():FinanceService{return$this->one(__FUNCTION__,fn()=>new FinanceService($this->db(),$this->finance(),$this->audits(),$this->roles()));} public function documentStatuses():DocumentStatus{return$this->one(__FUNCTION__,fn()=>new DocumentStatus());} public function documentStorage():PrivateDocumentStorage{return$this->one(__FUNCTION__,fn()=>new PrivateDocumentStorage($this->config['documents']));} public function documentService():MemberDocumentService{return$this->one(__FUNCTION__,fn()=>new MemberDocumentService($this->db(),$this->documents(),$this->applications(),$this->documentStorage(),$this->audits(),$this->roles(),$this->documentStatuses()));}
    public function render(string $view,array $data=[],int $status=200):\Ishep\Http\Response{extract($data,EXTR_SKIP);ob_start();require$this->base.'/templates/pages/'.$view.'.php';$content=(string)ob_get_clean();ob_start();require$this->base.'/templates/layouts/app.php';return new \Ishep\Http\Response((string)ob_get_clean(),$status);}
}
