<div class="form-card card shadow-sm mx-auto"><div class="card-body p-4 p-md-5">
<h1 class="h3">Create your account</h1><p class="text-secondary">Join ISHEP using a secure personal account.</p>
<form method="post" action="<?=e(url('/register'))?>" data-password-form><?=csrf_field()?>
<div class="mb-3"><label class="form-label" for="name">Full name</label><input class="form-control" id="name" name="name" value="<?=e(old('name'))?>" required maxlength="255" autocomplete="name" aria-invalid="<?=field_invalid('name')?>" aria-describedby="name-errors"><?php if(field_errors('name')):?><div id="name-errors" class="invalid-feedback d-block"><?=e(implode(' ',field_errors('name')))?></div><?php endif;?></div>
<div class="mb-3"><label class="form-label" for="email">Email</label><input class="form-control" id="email" name="email" type="email" value="<?=e(old('email'))?>" required maxlength="255" autocomplete="email" aria-invalid="<?=field_invalid('email')?>" aria-describedby="email-errors"><?php if(field_errors('email')):?><div id="email-errors" class="invalid-feedback d-block"><?=e(implode(' ',field_errors('email')))?></div><?php endif;?></div>
<div class="mb-3"><label class="form-label" for="membership_type_id">Membership type</label><select class="form-select" id="membership_type_id" name="membership_type_id" required aria-invalid="<?=field_invalid('membership_type_id')?>" aria-describedby="membership-errors"><option value="">Choose a membership type</option><?php foreach($membershipTypes as$type):?><option value="<?=e($type['id'])?>" <?=old('membership_type_id')==(string)$type['id']?'selected':''?>><?=e($type['name'])?></option><?php endforeach;?></select><?php if(field_errors('membership_type_id')):?><div id="membership-errors" class="invalid-feedback d-block"><?=e(implode(' ',field_errors('membership_type_id')))?></div><?php endif;?></div>
<div class="mb-3"><label class="form-label" for="password">Password</label><div class="input-group"><input class="form-control" id="password" name="password" type="password" required minlength="<?=e(Ishep\Security\PasswordPolicy::MIN_LENGTH)?>" autocomplete="new-password" data-password aria-invalid="<?=field_invalid('password')?>" aria-describedby="password-requirements password-errors"><button class="btn btn-outline-secondary" type="button" data-password-toggle="password" aria-label="Show password" aria-pressed="false">Show password</button></div><?php if(field_errors('password')):?><div id="password-errors" class="invalid-feedback d-block"><?=e(implode(' ',field_errors('password')))?></div><?php endif;?><div id="password-requirements" class="mt-2"><p class="small mb-1 fw-semibold">Password requirements</p><ul class="list-unstyled small mb-1"><?php foreach($passwordRequirements as$key=>$label):?><li class="text-secondary" data-password-rule="<?=e($key)?>" <?=$key==='length'?'data-min-length="'.e(Ishep\Security\PasswordPolicy::MIN_LENGTH).'"':''?>><span data-state-icon aria-hidden="true">○</span> <?=e($label)?></li><?php endforeach;?></ul><p class="text-secondary small" aria-live="polite" data-password-overall>Password requirements have not been evaluated yet.</p></div></div>
<div class="mb-3"><label class="form-label" for="password_confirmation">Confirm password</label><div class="input-group"><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" required autocomplete="new-password" data-password-confirmation aria-invalid="<?=field_invalid('password')?>" aria-describedby="confirmation-feedback"><button class="btn btn-outline-secondary" type="button" data-password-toggle="password_confirmation" aria-label="Show password" aria-pressed="false">Show password</button></div><p id="confirmation-feedback" class="text-secondary small mt-1" aria-live="polite" data-confirmation-feedback>Enter the password again.</p></div>
<div class="form-check mb-3"><input class="form-check-input" id="terms" name="terms" value="1" type="checkbox" required <?=old('terms')?'checked':''?> aria-invalid="<?=field_invalid('terms')?>"><label class="form-check-label" for="terms">I accept the terms</label><?php if(field_errors('terms')):?><div class="invalid-feedback d-block"><?=e(implode(' ',field_errors('terms')))?></div><?php endif;?></div>
<button class="btn btn-primary w-100" type="submit">Create account</button></form></div></div>
