<?php
namespace Ishep\Http\Controllers;
use Ishep\Bootstrap\Application as App;use Ishep\Http\{Request,Response};use Ishep\Security\PasswordPolicy;use Ishep\Validation\Validator;use PDOException;use Throwable;
final class AuthController
{
    private function app():App{return App::instance();}
    private function fail(array $errors,array $old,string $to):Response{unset($old['password'],$old['password_confirmation'],$old['_token'],$old['role'],$old['roles'],$old['account_status']);$this->app()->session()->flash('errors',$errors);$this->app()->session()->flash('old',$old);return Response::redirect(url($to));}
    public function form(string $view,array $data=[]):Response{return$this->app()->render($view,$data);}
    public function registerForm():Response{return$this->app()->render('auth/register',['membershipTypes'=>$this->app()->memberships()->active(),'passwordRequirements'=>(new PasswordPolicy())->requirements()]);}
    public function register(Request $request):Response
    {
        $data=$request->input;$data['name']=trim((string)($data['name']??''));$data['email']=mb_strtolower(trim((string)($data['email']??'')));$data['membership_type_id']=trim((string)($data['membership_type_id']??''));
        $errors=(new Validator())->validate($data,['name'=>['required','max:255'],'email'=>['required','email','max:255'],'membership_type_id'=>['required'],'password'=>['required','confirmed'],'terms'=>['accepted']]);
        $policyErrors=(new PasswordPolicy())->errors((string)($data['password']??''));if($policyErrors)$errors['password']=$policyErrors;
        $membershipId=ctype_digit($data['membership_type_id'])?(int)$data['membership_type_id']:0;if(!$membershipId||!$this->app()->memberships()->activeById($membershipId))$errors['membership_type_id'][]='Select a valid active membership type.';
        if($errors)return$this->fail($errors,$data,'/register');if($this->app()->users()->byEmail($data['email']))return$this->fail(['email'=>['An account already uses this email.']],$data,'/register');
        try{$id=$this->app()->registration()->register($data['name'],$data['email'],$data['password'],$membershipId);$this->app()->session()->put('user_id',$id);$this->app()->session()->regenerate();$this->app()->csrf()->rotate();$this->app()->session()->flash('status','Your account has been created.');return Response::redirect(url('/dashboard'));}
        catch(PDOException $exception){$this->app()->logger()->log('error','Registration database failure',['exception'=>get_class($exception),'driver_code'=>$exception->errorInfo[1]??$exception->getCode()]);$duplicate=($exception->getCode()==='23000'||($exception->errorInfo[0]??null)==='23000');return$this->fail(['email'=>[$duplicate?'An account already uses this email.':'Registration could not be completed safely. Please try again.']],$data,'/register');}
        catch(Throwable $exception){$this->app()->logger()->log('error','Registration transaction failure',['exception'=>get_class($exception)]);return$this->fail(['registration'=>['Registration could not be completed safely. Please try again.']],$data,'/register');}
    }
    public function login(Request $request):Response{$email=mb_strtolower(trim((string)($request->input['email']??'')));$key='login:'.hash('sha256',$email.'|'.$request->ip());if($this->app()->limiter()->blocked($key))return$this->fail(['email'=>['Too many login attempts. Try again in about 60 seconds.']],['email'=>$email],'/login');if(!$this->app()->auth()->attempt($email,(string)($request->input['password']??''))){$this->app()->limiter()->hit($key);return$this->fail(['email'=>['The provided credentials are invalid.']],['email'=>$email],'/login');}$this->app()->limiter()->clear($key);$this->app()->csrf()->rotate();return Response::redirect(url('/dashboard'));}
    public function logout(Request $request):Response{$this->app()->auth()->logout();return Response::redirect(url('/'));}
    public function forgot(Request $request):Response{$email=mb_strtolower(trim((string)($request->input['email']??'')));$this->app()->passwordReset()->request($email,(string)$this->app()->config('app.url'));$this->app()->session()->flash('status','If an account exists, a password reset link has been sent.');return Response::redirect(url('/forgot-password'));}
    public function reset(Request $request):Response{$data=$request->input;$data['email']=mb_strtolower(trim((string)($data['email']??'')));$errors=(new Validator())->validate($data,['email'=>['required','email'],'token'=>['required'],'password'=>['required','confirmed']]);$policy=(new PasswordPolicy())->errors((string)($data['password']??''));if($policy)$errors['password']=$policy;if($errors)return$this->fail($errors,['email'=>$data['email'],'token'=>$data['token']??''],'/reset-password/'.rawurlencode((string)($data['token']??'')));if(!$this->app()->passwordReset()->reset($data['email'],$data['token'],$data['password']))return$this->fail(['email'=>['This password reset link is invalid or expired.']],['email'=>$data['email'],'token'=>$data['token']],'/reset-password/'.rawurlencode($data['token']));$this->app()->session()->flash('status','Your password has been reset.');return Response::redirect(url('/login'));}
}
