<?php
namespace Ishep\Http\Controllers;
use Ishep\Bootstrap\Application as App;use Ishep\Http\{Request,Response};use Ishep\Validation\Validator;
final class AuthController
{
    private function app():App{return App::instance();} private function fail(array $errors,array $old,string $to):Response{$safe=$old;unset($safe['password'],$safe['password_confirmation'],$safe['_token']);$this->app()->session()->flash('errors',$errors);$this->app()->session()->flash('old',$safe);return Response::redirect(url($to));}
    public function form(string $view,array $data=[]):Response{return$this->app()->render($view,$data);}
    public function register(Request $r):Response{$data=$r->input;$data['email']=mb_strtolower(trim((string)($data['email']??'')));$v=(new Validator())->validate($data,['name'=>['required','max:255'],'email'=>['required','email','max:255'],'password'=>['required','min:8','confirmed'],'terms'=>['accepted']]);if(!preg_match('/[A-Z]/',$data['password']??'')||!preg_match('/[a-z]/',$data['password']??'')||!preg_match('/\d/',$data['password']??''))$v['password'][]='Password must contain upper/lowercase letters and a number.';if($v)return$this->fail($v,$data,'/register');if($this->app()->users()->byEmail($data['email']))return$this->fail(['email'=>['An account already uses this email.']],$data,'/register');$id=$this->app()->registration()->register(trim($data['name']),$data['email'],$data['password']);$this->app()->session()->put('user_id',$id);$this->app()->session()->regenerate();$this->app()->csrf()->rotate();$this->app()->session()->flash('status','Your account has been created.');return Response::redirect(url('/dashboard'));}
    public function login(Request $r):Response{$email=mb_strtolower(trim((string)($r->input['email']??'')));$key='login:'.hash('sha256',$email.'|'.$r->ip());if($this->app()->limiter()->blocked($key))return$this->fail(['email'=>['Too many login attempts. Try again in about 60 seconds.']],['email'=>$email],'/login');if(!$this->app()->auth()->attempt($email,(string)($r->input['password']??''))){$this->app()->limiter()->hit($key);return$this->fail(['email'=>['The provided credentials are invalid.']],['email'=>$email],'/login');}$this->app()->limiter()->clear($key);$this->app()->csrf()->rotate();return Response::redirect(url('/dashboard'));}
    public function logout(Request $r):Response{$this->app()->auth()->logout();return Response::redirect(url('/'));}
    public function forgot(Request $r):Response{$email=mb_strtolower(trim((string)($r->input['email']??'')));$this->app()->passwordReset()->request($email,(string)$this->app()->config('app.url'));$this->app()->session()->flash('status','If an account exists, a password reset link has been sent.');return Response::redirect(url('/forgot-password'));}
    public function reset(Request $r):Response{$data=$r->input;$data['email']=mb_strtolower(trim((string)($data['email']??'')));$v=(new Validator())->validate($data,['email'=>['required','email'],'token'=>['required'],'password'=>['required','min:8','confirmed']]);if($v)return$this->fail($v,['email'=>$data['email'],'token'=>$data['token']??''],'/reset-password/'.rawurlencode((string)($data['token']??'')));if(!$this->app()->passwordReset()->reset($data['email'],$data['token'],$data['password']))return$this->fail(['email'=>['This password reset link is invalid or expired.']],['email'=>$data['email'],'token'=>$data['token']],'/reset-password/'.rawurlencode($data['token']));$this->app()->session()->flash('status','Your password has been reset.');return Response::redirect(url('/login'));}
}
