<?php
namespace Ishep\Http\Controllers;
use Throwable;use DomainException;use Ishep\Bootstrap\Application as App;use Ishep\Http\{Request,Response};
final class MembershipReviewController
{
 private function app():App{return App::instance();}private function uid():int{return(int)$this->app()->session()->get('user_id');}
 public function index(Request $r):Response{$status=trim((string)($r->query['status']??''));$search=trim((string)($r->query['q']??''));return$this->app()->render('admin/applications/index',['applications'=>$this->app()->applications()->queue($status,$search),'counts'=>$this->app()->applications()->counts(),'filter'=>$status,'search'=>$search,'statuses'=>$this->app()->applicationStatuses()]);}
 public function show(Request $r):Response{$a=$this->app()->applications()->byNumber((string)$r->get('reference'));return$a?$this->app()->render('admin/applications/show',['application'=>$a,'events'=>$this->app()->applications()->events((int)$a['id'],true),'statuses'=>$this->app()->applicationStatuses()]):$this->app()->render('errors/404',[],404);}
 private function action(Request $r,string $action):Response{$number=(string)$r->get('reference');if(!$this->app()->applications()->byNumber($number))return$this->app()->render('errors/404',[],404);try{$this->app()->applicationService()->review($number,$this->uid(),$action,(string)($r->input['decision_reason']??''),(string)($r->input['internal_note']??''),$r->ip());$this->app()->session()->flash('status','Application status updated.');return Response::redirect(url('/admin/membership-applications/'.$number));}catch(Throwable $e){$message=$e instanceof DomainException?$e->getMessage():'The review action could not be completed safely.';if(!$e instanceof DomainException)$this->app()->logger()->log('error','Membership review failed',['exception'=>get_class($e),'reviewer_id'=>$this->uid()]);$this->app()->session()->flash('errors',['application'=>[$message]]);return Response::redirect(url('/admin/membership-applications/'.$number));}}
 public function start(Request $r):Response{return$this->action($r,'start-review');}public function approve(Request $r):Response{return$this->action($r,'approve');}public function reject(Request $r):Response{return$this->action($r,'reject');}
}
