<?php
namespace Ishep\Repositories;use PDO;
final class FinanceRepository
{
 public function __construct(private PDO $db){}
 public function feeByReference(string $ref):?array{$s=$this->db->prepare('SELECT f.*,m.name membership_type_name FROM membership_fee_schedules f JOIN membership_types m ON m.id=f.membership_type_id WHERE f.fee_reference=?');$s->execute([$ref]);return$s->fetch()?:null;}
 public function fees():array{return$this->db->query('SELECT f.*,m.name membership_type_name,(SELECT COUNT(*) FROM invoice_items ii JOIN invoices i ON i.id=ii.invoice_id WHERE i.membership_id IN(SELECT id FROM memberships WHERE membership_type_id=f.membership_type_id) AND i.issued_at>=f.effective_from) usage_count FROM membership_fee_schedules f JOIN membership_types m ON m.id=f.membership_type_id ORDER BY f.effective_from DESC,f.id DESC')->fetchAll();}
 public function effectiveFee(int $type,?string $date=null):?array{$date??=gmdate('Y-m-d');$s=$this->db->prepare('SELECT * FROM membership_fee_schedules WHERE membership_type_id=? AND active=1 AND effective_from<=? AND(effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC,id DESC LIMIT 1');$s->execute([$type,$date,$date]);return$s->fetch()?:null;}
 public function overlappingFee(int $type,string $from,?string $to,?int $except=null):bool{$sql='SELECT 1 FROM membership_fee_schedules WHERE membership_type_id=? AND active=1 AND effective_from<=COALESCE(?,\'9999-12-31\') AND COALESCE(effective_to,\'9999-12-31\')>=?';$v=[$type,$to,$from];if($except){$sql.=' AND id<>?';$v[]=$except;}$s=$this->db->prepare($sql.' LIMIT 1');$s->execute($v);return(bool)$s->fetchColumn();}
 public function createFee(array $v):int{$s=$this->db->prepare('INSERT INTO membership_fee_schedules(fee_reference,membership_type_id,amount,currency,billing_period,effective_from,effective_to,active,created_by)VALUES(?,?,?,?,?,?,?,1,?)');$s->execute($v);return(int)$this->db->lastInsertId();}
 public function deactivateFee(int $id):void{$this->db->prepare('UPDATE membership_fee_schedules SET active=0 WHERE id=?')->execute([$id]);}
 public function membershipByApplication(int $app):?array{$s=$this->db->prepare('SELECT * FROM memberships WHERE membership_application_id=?');$s->execute([$app]);return$s->fetch()?:null;}
 public function membershipForUser(int $uid):?array{$s=$this->db->prepare('SELECT m.*,mt.name membership_type_name,a.application_number FROM memberships m JOIN membership_types mt ON mt.id=m.membership_type_id JOIN membership_applications a ON a.id=m.membership_application_id WHERE m.user_id=? ORDER BY m.id DESC LIMIT 1');$s->execute([$uid]);return$s->fetch()?:null;}
 public function createMembership(array $v):int{$s=$this->db->prepare('INSERT INTO memberships(membership_number,user_id,membership_application_id,membership_type_id,status)VALUES(?,?,?,?,?)');$s->execute($v);return(int)$this->db->lastInsertId();}
 public function setMembershipStatus(int $id,string $status):void{$sql='UPDATE memberships SET status=?,updated_at=UTC_TIMESTAMP()'.($status==='active'?',activated_at=COALESCE(activated_at,UTC_TIMESTAMP()),starts_at=COALESCE(starts_at,CURDATE())':'').' WHERE id=?';$this->db->prepare($sql)->execute([$status,$id]);}
 public function invoiceByMembership(int $id):?array{$s=$this->db->prepare('SELECT * FROM invoices WHERE membership_id=?');$s->execute([$id]);return$s->fetch()?:null;}
 public function createInvoice(array $v,string $description,string $amount):int{$s=$this->db->prepare('INSERT INTO invoices(invoice_number,user_id,membership_id,membership_application_id,currency,subtotal,total,balance_due,status,due_at)VALUES(?,?,?,?,?,?,?,?,\'issued\',DATE_ADD(UTC_TIMESTAMP(),INTERVAL 30 DAY))');$s->execute($v);$id=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO invoice_items(invoice_id,description,quantity,unit_amount,line_total)VALUES(?,?,1,?,?)')->execute([$id,$description,$amount,$amount]);return$id;}
 public function invoice(string $ref,?int $owner=null):?array{$sql='SELECT i.*,u.name member_name,u.email,m.membership_number,mt.name membership_type_name,a.application_number FROM invoices i JOIN users u ON u.id=i.user_id JOIN memberships m ON m.id=i.membership_id JOIN membership_types mt ON mt.id=m.membership_type_id JOIN membership_applications a ON a.id=i.membership_application_id WHERE i.invoice_number=?'.($owner?' AND i.user_id=?':'');$s=$this->db->prepare($sql);$s->execute($owner?[$ref,$owner]:[$ref]);return$s->fetch()?:null;}
 public function invoiceById(int $id):?array{$s=$this->db->prepare('SELECT * FROM invoices WHERE id=? FOR UPDATE');$s->execute([$id]);return$s->fetch()?:null;}
 public function invoiceItems(int $id):array{$s=$this->db->prepare('SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY id');$s->execute([$id]);return$s->fetchAll();}
 public function invoices(?int $owner=null,?string $status=null):array{$w=[];$v=[];if($owner){$w[]='i.user_id=?';$v[]=$owner;}if($status){$w[]='i.status=?';$v[]=$status;}$s=$this->db->prepare('SELECT i.*,u.name member_name,m.membership_number FROM invoices i JOIN users u ON u.id=i.user_id JOIN memberships m ON m.id=i.membership_id '.($w?'WHERE '.implode(' AND ',$w):'').' ORDER BY i.issued_at DESC LIMIT 100');$s->execute($v);return$s->fetchAll();}
 public function payment(string $ref,?int $owner=null):?array{$sql='SELECT p.*,u.name member_name,r.payment_reference reversed_by_reference FROM payments p JOIN users u ON u.id=p.user_id LEFT JOIN payments r ON r.reversal_of_payment_id=p.id WHERE p.payment_reference=?'.($owner?' AND p.user_id=?':'');$s=$this->db->prepare($sql);$s->execute($owner?[$ref,$owner]:[$ref]);return$s->fetch()?:null;}
 public function payments(?int $owner=null):array{$s=$this->db->prepare('SELECT p.*,u.name member_name,i.invoice_number FROM payments p JOIN users u ON u.id=p.user_id LEFT JOIN payment_allocations pa ON pa.payment_id=p.id LEFT JOIN invoices i ON i.id=pa.invoice_id WHERE (? IS NULL OR p.user_id=?) ORDER BY p.received_at DESC LIMIT 100');$s->execute([$owner,$owner]);return$s->fetchAll();}
 public function createPayment(array $v):int{$s=$this->db->prepare('INSERT INTO payments(payment_reference,user_id,amount,currency,payment_method,manual_reference,received_at,recorded_by,status,note,idempotency_key)VALUES(?,?,?,?,?,?,?, ?,\'completed\',?,?)');$s->execute($v);return(int)$this->db->lastInsertId();}
 public function allocate(int $payment,int $invoice,string $amount):void{$this->db->prepare('INSERT INTO payment_allocations(payment_id,invoice_id,amount)VALUES(?,?,?)')->execute([$payment,$invoice,$amount]);}
 public function recalculateInvoice(int $id):array{$s=$this->db->prepare("SELECT i.total,COALESCE(SUM(CASE WHEN p.status='completed' THEN pa.amount-COALESCE((SELECT SUM(r.amount) FROM refunds r WHERE r.payment_id=p.id),0) ELSE 0 END),0) paid FROM invoices i LEFT JOIN payment_allocations pa ON pa.invoice_id=i.id LEFT JOIN payments p ON p.id=pa.payment_id WHERE i.id=? GROUP BY i.id");$s->execute([$id]);$r=$s->fetch();$paid=(string)$r['paid'];$balance=\Ishep\Support\Money::decimal(\Ishep\Support\Money::minor((string)$r['total'])-\Ishep\Support\Money::minor($paid));$status=\Ishep\Support\Money::minor($balance)===0?'paid':(\Ishep\Support\Money::minor($paid)>0?'partially_paid':'issued');$this->db->prepare('UPDATE invoices SET amount_paid=?,balance_due=?,status=?,paid_at=IF(?=\'paid\',COALESCE(paid_at,UTC_TIMESTAMP()),NULL) WHERE id=?')->execute([$paid,$balance,$status,$status,$id]);return['paid'=>$paid,'balance'=>$balance,'status'=>$status];}
 public function createReversal(array $v):int{$s=$this->db->prepare('INSERT INTO payments(payment_reference,user_id,amount,currency,payment_method,manual_reference,received_at,recorded_by,status,note,reversal_of_payment_id,reversal_reason,idempotency_key)VALUES(?,?,?,?,?,?,UTC_TIMESTAMP(),?,\'reversal\',?,?,?,?)');$s->execute($v);return(int)$this->db->lastInsertId();}
 public function allocationForPayment(int $id):?array{$s=$this->db->prepare('SELECT pa.*,i.membership_id FROM payment_allocations pa JOIN invoices i ON i.id=pa.invoice_id WHERE pa.payment_id=?');$s->execute([$id]);return$s->fetch()?:null;}
 public function markReversed(int $id):void{$this->db->prepare("UPDATE payments SET status='reversed' WHERE id=? AND status='completed'")->execute([$id]);}
 public function refundRequests(?int $owner=null):array{$s=$this->db->prepare('SELECT rr.*,p.payment_reference,u.name member_name FROM refund_requests rr JOIN payments p ON p.id=rr.payment_id JOIN users u ON u.id=rr.requested_by WHERE(? IS NULL OR rr.requested_by=?) ORDER BY rr.created_at DESC LIMIT 100');$s->execute([$owner,$owner]);return$s->fetchAll();}
 public function refundRequest(string $ref):?array{$s=$this->db->prepare('SELECT rr.*,p.payment_reference,p.user_id,p.amount payment_amount,p.currency FROM refund_requests rr JOIN payments p ON p.id=rr.payment_id WHERE rr.request_reference=? FOR UPDATE');$s->execute([$ref]);return$s->fetch()?:null;}
 public function refundable(int $payment):string{$s=$this->db->prepare("SELECT p.amount-COALESCE((SELECT SUM(r.amount) FROM refunds r WHERE r.payment_id=p.id),0)-COALESCE((SELECT SUM(rr.requested_amount) FROM refund_requests rr WHERE rr.payment_id=p.id AND rr.status IN('requested','under_review','approved')),0) FROM payments p WHERE p.id=? AND p.status='completed'");$s->execute([$payment]);return(string)($s->fetchColumn()?:'0.00');}
 public function createRefundRequest(array $v):void{$this->db->prepare("INSERT INTO refund_requests(request_reference,payment_id,requested_by,requested_amount,reason,status)VALUES(?,?,?,?,?,'requested')")->execute($v);}
 public function decideRefund(int $id,string $status,int $actor,string $reason):void{$this->db->prepare('UPDATE refund_requests SET status=?,reviewed_by=?,reviewed_at=UTC_TIMESTAMP(),decision_reason=? WHERE id=?')->execute([$status,$actor,$reason?:null,$id]);}
 public function createRefund(array $v):void{$this->db->prepare('INSERT INTO refunds(refund_reference,refund_request_id,payment_id,amount,method,processed_by,processed_at,manual_reference)VALUES(?,?,?,?,?,?,UTC_TIMESTAMP(),?)')->execute($v);}
 public function event(string $type,string $ref,?int $actor,?string $from,?string $to,string $action,?string $note=null):void{$this->db->prepare('INSERT INTO finance_events(entity_type,entity_reference,actor_user_id,previous_status,new_status,action,note)VALUES(?,?,?,?,?,?,?)')->execute([$type,$ref,$actor,$from,$to,$action,$note]);}
 public function counts():array{$q="SELECT (SELECT COUNT(*) FROM invoices WHERE status='issued') awaiting,(SELECT COUNT(*) FROM invoices WHERE status='partially_paid') partial,(SELECT COUNT(*) FROM payments WHERE status='completed' AND DATE(received_at)=UTC_DATE()) today,(SELECT COUNT(*) FROM refund_requests WHERE status IN('requested','under_review')) refunds,(SELECT COUNT(*) FROM memberships WHERE status='awaiting_fee_configuration') awaiting_fee";return$this->db->query($q)->fetch()?:[];}
}
