<?php
namespace Ishep\Repositories;
use PDO;use Ishep\Services\MembershipApplicationStatus;
final class MembershipApplicationRepository
{
 public function __construct(private PDO $db){}
 private function base():string{return 'SELECT a.*,u.name,u.email,mt.name membership_type_name,mt.fee,mp.telephone,mp.organisation,mp.job_title,p.name province_name,pr.name profession_name,r.name reviewer_name FROM membership_applications a JOIN users u ON u.id=a.user_id JOIN membership_types mt ON mt.id=a.membership_type_id LEFT JOIN member_profiles mp ON mp.user_id=u.id LEFT JOIN provinces p ON p.id=mp.province_id LEFT JOIN professions pr ON pr.id=mp.profession_id LEFT JOIN users r ON r.id=a.reviewed_by ';}
 public function latestForUser(int $uid):?array{$s=$this->db->prepare($this->base().'WHERE a.user_id=? ORDER BY a.id DESC LIMIT 1');$s->execute([$uid]);return$s->fetch()?:null;}
 public function byNumber(string $number):?array{$s=$this->db->prepare($this->base().'WHERE a.application_number=? LIMIT 1');$s->execute([$number]);return$s->fetch()?:null;}
 public function create(int $uid,int $type,string $number):int{$s=$this->db->prepare("INSERT INTO membership_applications(application_number,user_id,membership_type_id,status,created_at,updated_at) VALUES (?,?,?,'draft',UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute([$number,$uid,$type]);return(int)$this->db->lastInsertId();}
 public function updateDraft(int $id,int $type):void{$this->db->prepare('UPDATE membership_applications SET membership_type_id=?,updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([$type,$id]);}
 public function transition(int $id,string $status,int $actor,?string $reason=null,?string $internal=null):void{$sets=['status=?','updated_at=UTC_TIMESTAMP()'];$v=[$status];if($status==='submitted'){$sets[]='submitted_at=UTC_TIMESTAMP()';$sets[]='declaration_at=UTC_TIMESTAMP()';}if($status==='under_review'){$sets[]='reviewed_by=?';$sets[]='review_started_at=UTC_TIMESTAMP()';$v[]=$actor;}if(in_array($status,['approved','rejected'],true)){$sets[]='reviewed_by=?';$sets[]='decided_at=UTC_TIMESTAMP()';$sets[]='decision_reason=?';$sets[]='internal_note=?';array_push($v,$actor,$reason,$internal);}if($status==='draft'){$sets[]='reviewed_by=NULL';$sets[]='review_started_at=NULL';$sets[]='decided_at=NULL';$sets[]='decision_reason=NULL';$sets[]='internal_note=NULL';}$v[]=$id;$this->db->prepare('UPDATE membership_applications SET '.implode(',',$sets).' WHERE id=?')->execute($v);}
 public function event(int $id,?int $actor,?string $from,string $to,?string $note):void{$this->db->prepare('INSERT INTO membership_application_events(membership_application_id,actor_user_id,previous_status,new_status,note,created_at) VALUES (?,?,?,?,?,UTC_TIMESTAMP())')->execute([$id,$actor,$from,$to,$note]);}
 public function events(int $id,bool $staff=false):array{$s=$this->db->prepare('SELECT e.previous_status,e.new_status,e.note,e.created_at,u.name actor_name FROM membership_application_events e LEFT JOIN users u ON u.id=e.actor_user_id WHERE e.membership_application_id=? ORDER BY e.id');$s->execute([$id]);$rows=$s->fetchAll();if(!$staff)foreach($rows as &$row)if($row['new_status']==='under_review')$row['note']=null;return$rows;}
 public function queue(?string $status,string $search,int $limit=50):array{$w=[];$v=[];if($status&&in_array($status,MembershipApplicationStatus::ALL,true)){$w[]='a.status=?';$v[]=$status;}if($search!==''){$w[]='(a.application_number LIKE ? OR u.name LIKE ? OR u.email LIKE ?)';$term='%'.$search.'%';array_push($v,$term,$term,$term);}$s=$this->db->prepare($this->base().($w?'WHERE '.implode(' AND ',$w).' ':'').'ORDER BY a.updated_at DESC LIMIT '.max(1,min(100,$limit)));$s->execute($v);return$s->fetchAll();}
 public function counts():array{$out=array_fill_keys(['submitted','under_review','approved','rejected'],0);$s=$this->db->prepare("SELECT status,COUNT(*) total FROM membership_applications WHERE status IN ('submitted','under_review','approved','rejected') GROUP BY status");$s->execute();foreach($s->fetchAll()as$r)$out[$r['status']]=(int)$r['total'];return$out;}
}
