<?php
namespace Ishep\Repositories;use PDO;use InvalidArgumentException;
final class PortalRepository
{public function __construct(private PDO $db){}private function meta(string $d):array{if($d==='career')return['o'=>'career_opportunities','a'=>'career_applications','e'=>'career_application_events','fk'=>'career_opportunity_id','efk'=>'career_application_id','join'=>'LEFT JOIN provinces p ON p.id=o.province_id LEFT JOIN professions pr ON pr.id=o.profession_id','extra'=>'p.name province_name,pr.name profession_name'];if($d==='bursary')return['o'=>'bursary_opportunities','a'=>'bursary_applications','e'=>'bursary_application_events','fk'=>'bursary_opportunity_id','efk'=>'bursary_application_id','join'=>'','extra'=>'NULL province_name,NULL profession_name'];throw new InvalidArgumentException('Invalid portal domain.');}
public function publicList(string $d,array $f=[],int $limit=50):array{$m=$this->meta($d);$where=["o.status='published'","o.closing_date>=CURDATE()"];$v=[];$q=trim((string)($f['q']??''));if($q!==''){$where[]=$d==='career'?'(o.title LIKE ? OR o.organisation LIKE ? OR o.summary LIKE ?)':'(o.title LIKE ? OR o.provider LIKE ? OR o.field_of_study LIKE ?)';$term='%'.$q.'%';array_push($v,$term,$term,$term);}foreach($d==='career'?['province_id','profession_id','employment_type']:['field_of_study','study_level'] as $key)if(trim((string)($f[$key]??''))!==''){$where[]='o.'.$key.'=?';$v[]=trim((string)$f[$key]);}$sql='SELECT o.**,'.$m['extra'].' FROM '.$m['o'].' o '.$m['join'].' WHERE '.implode(' AND ',$where).' ORDER BY o.closing_date ASC,o.id DESC LIMIT '.max(1,min(100,$limit));$sql=str_replace('o.**','o.*',$sql);$s=$this->db->prepare($sql);$s->execute($v);return$s->fetchAll();}
public function opportunity(string $d,string $ref,bool $staff=false):?array{$m=$this->meta($d);$s=$this->db->prepare('SELECT o.*,'.$m['extra'].' FROM '.$m['o'].' o '.$m['join'].' WHERE o.opportunity_reference=?'.($staff?'':" AND o.status IN('published','closed')").' LIMIT 1');$s->execute([$ref]);return$s->fetch()?:null;}
public function opportunities(string $d):array{$m=$this->meta($d);return$this->db->query('SELECT o.*,'.$m['extra'].' FROM '.$m['o'].' o '.$m['join'].' ORDER BY o.updated_at DESC LIMIT 100')->fetchAll();}
public function createOpportunity(string $d,array $data,int $actor,string $ref):int{$m=$this->meta($d);if($d==='career'){$sql='INSERT INTO '.$m['o'].'(opportunity_reference,title,organisation,location,province_id,profession_id,employment_type,work_arrangement,summary,description,requirements,application_instructions,external_url,closing_date,status,created_by,updated_by)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,\'draft\',?,?)';$v=[$ref,$data['title'],$data['organisation'],$data['location']?:null,$data['province_id']?:null,$data['profession_id']?:null,$data['employment_type'],$data['work_arrangement']?:null,$data['summary'],$data['description'],$data['requirements'],$data['application_instructions']?:null,$data['external_url']?:null,$data['closing_date'],$actor,$actor];}else{$sql='INSERT INTO '.$m['o'].'(opportunity_reference,title,provider,field_of_study,description,eligibility_criteria,benefits,study_level,opening_date,closing_date,status,created_by,updated_by)VALUES(?,?,?,?,?,?,?,?,?,?,\'draft\',?,?)';$v=[$ref,$data['title'],$data['provider'],$data['field_of_study'],$data['description'],$data['eligibility_criteria'],$data['benefits'],$data['study_level'],$data['opening_date'],$data['closing_date'],$actor,$actor];}$s=$this->db->prepare($sql);$s->execute($v);return(int)$this->db->lastInsertId();}
public function setOpportunityStatus(string $d,int $id,string $status,int $actor):void{$m=$this->meta($d);$this->db->prepare('UPDATE '.$m['o'].' SET status=?,updated_by=?,published_at=IF(?=\'published\',COALESCE(published_at,UTC_TIMESTAMP()),published_at),updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([$status,$actor,$status,$id]);}
public function applicationForUser(string $d,int $opp,int $uid):?array{$m=$this->meta($d);$s=$this->db->prepare('SELECT a.*,o.opportunity_reference,o.title FROM '.$m['a'].' a JOIN '.$m['o'].' o ON o.id=a.'.$m['fk'].' WHERE a.'.$m['fk'].'=? AND a.applicant_user_id=?');$s->execute([$opp,$uid]);return$s->fetch()?:null;}
public function application(string $d,string $ref,?int $owner=null):?array{$m=$this->meta($d);$sql='SELECT a.*,o.opportunity_reference,o.title,u.name applicant_name,u.email FROM '.$m['a'].' a JOIN '.$m['o'].' o ON o.id=a.'.$m['fk'].' JOIN users u ON u.id=a.applicant_user_id WHERE a.application_reference=?'.($owner?' AND a.applicant_user_id=?':'');$s=$this->db->prepare($sql);$s->execute($owner?[$ref,$owner]:[$ref]);return$s->fetch()?:null;}
public function createApplication(string $d,int $opp,int $uid,string $ref):int{$m=$this->meta($d);$s=$this->db->prepare('INSERT INTO '.$m['a'].'(application_reference,'.$m['fk'].',applicant_user_id,status)VALUES(?,?,?,\'draft\')');$s->execute([$ref,$opp,$uid]);return(int)$this->db->lastInsertId();}
public function saveApplication(string $d,int $id,array $data):void{$m=$this->meta($d);if($d==='career'){$sql='UPDATE '.$m['a'].' SET cover_letter=?,experience_summary=?,updated_at=UTC_TIMESTAMP() WHERE id=?';$v=[$data['cover_letter'],$data['experience_summary'],$id];}else{$sql='UPDATE '.$m['a'].' SET institution=?,qualification=?,study_level=?,motivation=?,declaration_confirmed=?,updated_at=UTC_TIMESTAMP() WHERE id=?';$v=[$data['institution'],$data['qualification'],$data['study_level'],$data['motivation'],$data['declaration_confirmed'],$id];}$this->db->prepare($sql)->execute($v);}
public function transitionApplication(string $d,int $id,string $to,int $actor,?string $reason=null,?string $private=null):void{$m=$this->meta($d);$sets=['status=?','updated_at=UTC_TIMESTAMP()'];$v=[$to];if($to==='submitted')$sets[]='submitted_at=UTC_TIMESTAMP()';if($to==='under_review'){$sets[]='reviewed_by=?';$sets[]='review_started_at=UTC_TIMESTAMP()';$v[]=$actor;}if(in_array($to,['shortlisted','unsuccessful','hired','approved'],true)){$sets[]='reviewed_by=?';$sets[]='decided_at=UTC_TIMESTAMP()';$sets[]='decision_reason=?';$sets[]='private_reviewer_note=?';array_push($v,$actor,$reason,$private);}$v[]=$id;$this->db->prepare('UPDATE '.$m['a'].' SET '.implode(',',$sets).' WHERE id=?')->execute($v);}
public function event(string $d,int $id,?int $actor,?string $from,string $to,string $action,?string $note):void{$m=$this->meta($d);$this->db->prepare('INSERT INTO '.$m['e'].'('.$m['efk'].',actor_user_id,previous_status,new_status,action,note)VALUES(?,?,?,?,?,?)')->execute([$id,$actor,$from,$to,$action,$note]);}
public function events(string $d,int $id,bool $staff=false):array{$m=$this->meta($d);$s=$this->db->prepare('SELECT e.*,u.name actor_name FROM '.$m['e'].' e LEFT JOIN users u ON u.id=e.actor_user_id WHERE e.'.$m['efk'].'=? ORDER BY e.id');$s->execute([$id]);$rows=$s->fetchAll();if(!$staff)foreach($rows as &$r)if($r['new_status']==='under_review')$r['note']=null;return$rows;}
public function applications(string $d,?int $owner=null,?string $status=null):array{$m=$this->meta($d);$w=[];$v=[];if($owner){$w[]='a.applicant_user_id=?';$v[]=$owner;}if($status){$w[]='a.status=?';$v[]=$status;}$s=$this->db->prepare('SELECT a.*,o.title,u.name applicant_name FROM '.$m['a'].' a JOIN '.$m['o'].' o ON o.id=a.'.$m['fk'].' JOIN users u ON u.id=a.applicant_user_id '.($w?'WHERE '.implode(' AND ',$w):'').' ORDER BY a.updated_at DESC LIMIT 100');$s->execute($v);return$s->fetchAll();}
public function counts():array{$sql="SELECT (SELECT COUNT(*) FROM career_opportunities WHERE status='published') careers_published,(SELECT COUNT(*) FROM career_applications WHERE status='submitted') careers_open,(SELECT COUNT(*) FROM career_applications WHERE status='under_review') careers_review,(SELECT COUNT(*) FROM bursary_opportunities WHERE status='published') bursaries_published,(SELECT COUNT(*) FROM bursary_applications WHERE status='submitted') bursaries_open,(SELECT COUNT(*) FROM bursary_applications WHERE status='under_review') bursaries_review";return$this->db->query($sql)->fetch()?:[];}}
