-- Additive private-document workflow for the existing ishep_crm database.
USE `ishep_crm`;
CREATE TABLE IF NOT EXISTS `document_types` (
 `id` bigint unsigned NOT NULL AUTO_INCREMENT,`code` varchar(100) NOT NULL,`name` varchar(255) NOT NULL,`description` text DEFAULT NULL,`active` tinyint(1) NOT NULL DEFAULT 1,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `document_types_code_unique`(`code`),KEY `document_types_active_index`(`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `membership_document_requirements` (
 `id` bigint unsigned NOT NULL AUTO_INCREMENT,`membership_type_id` bigint unsigned NOT NULL,`document_type_id` bigint unsigned NOT NULL,`required` tinyint(1) NOT NULL DEFAULT 0,`active` tinyint(1) NOT NULL DEFAULT 1,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `membership_document_requirements_unique`(`membership_type_id`,`document_type_id`),KEY `membership_document_requirements_active_index`(`active`),
 CONSTRAINT `membership_document_requirements_type_foreign` FOREIGN KEY(`membership_type_id`) REFERENCES `membership_types`(`id`) ON DELETE CASCADE,
 CONSTRAINT `membership_document_requirements_document_foreign` FOREIGN KEY(`document_type_id`) REFERENCES `document_types`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `member_documents` (
 `id` bigint unsigned NOT NULL AUTO_INCREMENT,`document_reference` varchar(40) NOT NULL,`user_id` bigint unsigned NOT NULL,`membership_application_id` bigint unsigned NOT NULL,`document_type_id` bigint unsigned NOT NULL,`original_filename` varchar(255) NOT NULL,`storage_key` varchar(255) NOT NULL,`relative_path` varchar(500) NOT NULL,`detected_mime` varchar(100) NOT NULL,`extension` varchar(10) NOT NULL,`byte_size` bigint unsigned NOT NULL,`sha256` char(64) NOT NULL,`verification_status` varchar(32) NOT NULL DEFAULT 'pending',`uploaded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`verified_at` timestamp NULL DEFAULT NULL,`verified_by` bigint unsigned DEFAULT NULL,`rejection_reason` varchar(1000) DEFAULT NULL,`internal_note` varchar(2000) DEFAULT NULL,`replaced_document_id` bigint unsigned DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `member_documents_reference_unique`(`document_reference`),UNIQUE KEY `member_documents_storage_key_unique`(`storage_key`),KEY `member_documents_user_status_index`(`user_id`,`verification_status`),KEY `member_documents_application_index`(`membership_application_id`),KEY `member_documents_type_status_index`(`document_type_id`,`verification_status`),KEY `member_documents_reviewer_index`(`verified_by`),
 CONSTRAINT `member_documents_user_foreign` FOREIGN KEY(`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,CONSTRAINT `member_documents_application_foreign` FOREIGN KEY(`membership_application_id`) REFERENCES `membership_applications`(`id`) ON DELETE CASCADE,CONSTRAINT `member_documents_type_foreign` FOREIGN KEY(`document_type_id`) REFERENCES `document_types`(`id`) ON DELETE RESTRICT,CONSTRAINT `member_documents_verifier_foreign` FOREIGN KEY(`verified_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,CONSTRAINT `member_documents_replaced_foreign` FOREIGN KEY(`replaced_document_id`) REFERENCES `member_documents`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `member_document_events` (
 `id` bigint unsigned NOT NULL AUTO_INCREMENT,`member_document_id` bigint unsigned NOT NULL,`actor_user_id` bigint unsigned DEFAULT NULL,`event_type` varchar(50) NOT NULL,`previous_status` varchar(32) DEFAULT NULL,`new_status` varchar(32) NOT NULL,`note` varchar(1000) DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(`id`),KEY `member_document_events_document_index`(`member_document_id`,`created_at`),KEY `member_document_events_actor_index`(`actor_user_id`),CONSTRAINT `member_document_events_document_foreign` FOREIGN KEY(`member_document_id`) REFERENCES `member_documents`(`id`) ON DELETE CASCADE,CONSTRAINT `member_document_events_actor_foreign` FOREIGN KEY(`actor_user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO `document_types`(`code`,`name`,`description`,`active`,`created_at`,`updated_at`) VALUES('supporting_document','Supporting document','Optional supporting document; final requirements remain pending confirmation.',1,UTC_TIMESTAMP(),UTC_TIMESTAMP());
