<?php
declare(strict_types=1);

$base=dirname(__DIR__);
$composer=$base.'/vendor/autoload.php';
if(is_file($composer)){require$composer;}else{spl_autoload_register(static function(string $class)use($base):void{$prefix='Ishep\\';if(str_starts_with($class,$prefix)){$file=$base.'/src/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($file))require$file;}});require$base.'/src/Support/helpers.php';}

use Ishep\Bootstrap\Application;use Ishep\Routing\Router;use Ishep\Http\Request;use Ishep\Http\Controllers\{PublicController,AuthController,DashboardController,ProfileController,MembershipApplicationController,MembershipReviewController,MemberDocumentController,DocumentReviewController};use Ishep\Http\Middleware\{AuthMiddleware,ActiveAccountMiddleware,RoleMiddleware,CsrfMiddleware,GuestMiddleware,ApplicationReviewerMiddleware};

$app=new Application($base);$router=new Router();$public=new PublicController();$auth=new AuthController();$dash=new DashboardController();$profile=new ProfileController();$membership=new MembershipApplicationController();$review=new MembershipReviewController();$memberDocuments=new MemberDocumentController();$documentReview=new DocumentReviewController();$csrf=new CsrfMiddleware();$guest=[new GuestMiddleware()];$protected=[new AuthMiddleware(),new ActiveAccountMiddleware()];$reviewer=array_merge($protected,[new ApplicationReviewerMiddleware()]);
$router->get('/',fn($r)=>$public->page('home'));$router->get('/membership',fn($r)=>$public->page('placeholder',['title'=>'Membership','message'=>'Membership applications are coming in a later stage.']));$router->get('/careers',fn($r)=>$public->page('placeholder',['title'=>'Career Portal','message'=>'Career listings and applications are not yet implemented.']));$router->get('/bursaries',fn($r)=>$public->page('placeholder',['title'=>'Bursary Portal','message'=>'Bursary listings and applications are not yet implemented.']));$router->get('/verify-membership',fn($r)=>$public->page('placeholder',['title'=>'Membership Verification','message'=>'Secure public membership verification is not yet implemented.']));$router->get('/health',[$public,'health']);
$router->get('/register',fn($r)=>$auth->registerForm(),$guest);$router->post('/register',[$auth,'register'],array_merge([$csrf],$guest));$router->get('/login',fn($r)=>$auth->form('auth/login'),$guest);$router->post('/login',[$auth,'login'],array_merge([$csrf],$guest));$router->post('/logout',[$auth,'logout'],array_merge([$csrf],$protected));$router->get('/forgot-password',fn($r)=>$auth->form('auth/forgot'),$guest);$router->post('/forgot-password',[$auth,'forgot'],array_merge([$csrf],$guest));$router->get('/reset-password/{token}',fn($r)=>$auth->form('auth/reset',['token'=>$r->get('token'),'email'=>$r->query['email']??'']),$guest);$router->post('/reset-password',[$auth,'reset'],array_merge([$csrf],$guest));
$router->get('/dashboard',fn($r)=>$profile->dashboard(),$protected);$router->get('/profile',fn($r)=>$profile->show(),$protected);$router->get('/profile/edit',fn($r)=>$profile->edit(),$protected);$router->post('/profile',[$profile,'update'],array_merge([$csrf],$protected));$router->get('/dashboard/administrator',fn($r)=>$dash->show('staff','Administrator Dashboard'),array_merge($protected,[new RoleMiddleware('administrator')]));$router->get('/dashboard/finance',fn($r)=>$dash->show('staff','Finance Dashboard'),array_merge($protected,[new RoleMiddleware('finance')]));$router->get('/dashboard/super-user',fn($r)=>$dash->show('staff','Super User / IT Dashboard'),array_merge($protected,[new RoleMiddleware('super_user')]));
$router->get('/membership/application',fn($r)=>$membership->show(),$protected);$router->get('/membership/application/create',fn($r)=>$membership->create(),$protected);$router->post('/membership/application/save',[$membership,'save'],array_merge($protected,[$csrf]));$router->post('/membership/application/submit',[$membership,'submit'],array_merge($protected,[$csrf]));$router->post('/membership/application/withdraw',[$membership,'withdraw'],array_merge($protected,[$csrf]));
$router->get('/admin/membership-applications',[$review,'index'],$reviewer);$router->get('/admin/membership-applications/{reference}',[$review,'show'],$reviewer);$router->post('/admin/membership-applications/{reference}/start-review',[$review,'start'],array_merge($reviewer,[$csrf]));$router->post('/admin/membership-applications/{reference}/approve',[$review,'approve'],array_merge($reviewer,[$csrf]));$router->post('/admin/membership-applications/{reference}/reject',[$review,'reject'],array_merge($reviewer,[$csrf]));
$router->get('/membership/application/documents',fn($r)=>$memberDocuments->index(),$protected);$router->post('/membership/application/documents/upload',[$memberDocuments,'upload'],array_merge($protected,[$csrf]));$router->get('/membership/application/documents/{reference}/download',[$memberDocuments,'download'],$protected);$router->post('/membership/application/documents/{reference}/replace',[$memberDocuments,'replace'],array_merge($protected,[$csrf]));$router->post('/membership/application/documents/{reference}/remove',[$memberDocuments,'remove'],array_merge($protected,[$csrf]));
$router->get('/admin/documents',[$documentReview,'index'],$reviewer);$router->get('/admin/documents/{reference}',[$documentReview,'show'],$reviewer);$router->get('/admin/documents/{reference}/download',[$documentReview,'download'],$reviewer);$router->post('/admin/documents/{reference}/verify',[$documentReview,'verify'],array_merge($reviewer,[$csrf]));$router->post('/admin/documents/{reference}/reject',[$documentReview,'reject'],array_merge($reviewer,[$csrf]));

try{$response=$router->dispatch(Request::capture());if($response->status===404)$response=$app->render('errors/404',[],404);$response->send();}catch(Throwable $e){$app->logger()->log('error','Unhandled request exception',['exception'=>get_class($e),'message'=>$e->getMessage()]);$app->render('errors/500',['showDetail'=>$app->config('app.debug'),'detail'=>$e->getMessage()],500)->send();}
