<?php
declare(strict_types=1);

$base=dirname(__DIR__);
$composer=$base.'/vendor/autoload.php';
if(is_file($composer)){require$composer;}else{spl_autoload_register(static function(string $class)use($base):void{$prefix='Ishep\\';if(str_starts_with($class,$prefix)){$file=$base.'/src/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($file))require$file;}});require$base.'/src/Support/helpers.php';}

use Ishep\Bootstrap\Application;use Ishep\Routing\Router;use Ishep\Http\Request;use Ishep\Http\Controllers\{PublicController,AuthController,DashboardController};use Ishep\Http\Middleware\{AuthMiddleware,ActiveAccountMiddleware,RoleMiddleware,CsrfMiddleware};

$app=new Application($base);$router=new Router();$public=new PublicController();$auth=new AuthController();$dash=new DashboardController();$csrf=new CsrfMiddleware();$protected=[new AuthMiddleware(),new ActiveAccountMiddleware()];
$router->get('/',fn($r)=>$public->page('home'));$router->get('/membership',fn($r)=>$public->page('placeholder',['title'=>'Membership','message'=>'Membership applications are coming in a later stage.']));$router->get('/careers',fn($r)=>$public->page('placeholder',['title'=>'Career Portal','message'=>'Career listings and applications are not yet implemented.']));$router->get('/bursaries',fn($r)=>$public->page('placeholder',['title'=>'Bursary Portal','message'=>'Bursary listings and applications are not yet implemented.']));$router->get('/verify-membership',fn($r)=>$public->page('placeholder',['title'=>'Membership Verification','message'=>'Secure public membership verification is not yet implemented.']));$router->get('/health',[$public,'health']);
$router->get('/register',fn($r)=>$auth->form('auth/register'));$router->post('/register',[$auth,'register'],[$csrf]);$router->get('/login',fn($r)=>$auth->form('auth/login'));$router->post('/login',[$auth,'login'],[$csrf]);$router->post('/logout',[$auth,'logout'],array_merge([$csrf],$protected));$router->get('/forgot-password',fn($r)=>$auth->form('auth/forgot'));$router->post('/forgot-password',[$auth,'forgot'],[$csrf]);$router->get('/reset-password/{token}',fn($r)=>$auth->form('auth/reset',['token'=>$r->get('token'),'email'=>$r->query['email']??'']));$router->post('/reset-password',[$auth,'reset'],[$csrf]);
$router->get('/dashboard',fn($r)=>$dash->show('member','Member Dashboard'),$protected);$router->get('/dashboard/administrator',fn($r)=>$dash->show('staff','Administrator Dashboard'),array_merge($protected,[new RoleMiddleware('administrator')]));$router->get('/dashboard/finance',fn($r)=>$dash->show('staff','Finance Dashboard'),array_merge($protected,[new RoleMiddleware('finance')]));$router->get('/dashboard/super-user',fn($r)=>$dash->show('staff','Super User / IT Dashboard'),array_merge($protected,[new RoleMiddleware('super_user')]));

try{$response=$router->dispatch(Request::capture());if($response->status===404)$response=$app->render('errors/404',[],404);$response->send();}catch(Throwable $e){$app->logger()->log('error','Unhandled request exception',['exception'=>get_class($e),'message'=>$e->getMessage()]);$app->render('errors/500',['showDetail'=>$app->config('app.debug'),'detail'=>$e->getMessage()],500)->send();}
