@extends('layouts.app')
@section('content')<div class="container py-5"><h1>Application {{ $application->reference_number }}</h1><p><span class="badge text-bg-secondary">Status: {{ $application->status->value }}</span> Type: {{ $application->membershipType->name }}</p>
@if(in_array($application->status->value,['draft','query_sent']))
@if($application->membershipType->code==='company')<h2 class="h4">Organization</h2><form method="POST" action="{{ route('member.applications.organization',$application) }}" class="row g-2">@csrf @method('PUT')@foreach(['name','registration_number','contact_email','contact_phone','physical_address','website'] as $f)<div class="col-md-6"><label class="form-label" for="{{ $f }}">{{ str($f)->replace('_',' ')->title() }}</label><input class="form-control" id="{{ $f }}" name="{{ $f }}" value="{{ old($f,$application->organization?->$f) }}" @if(in_array($f,['name','contact_email','contact_phone'])) required @endif></div>@endforeach<div><button class="btn btn-outline-primary">Save organization</button></div></form>@endif
@if($application->membershipType->code==='student')<h2 class="h4 mt-4">Student eligibility</h2><form method="POST" action="{{ route('member.applications.student',$application) }}" class="row g-2">@csrf @method('PUT')<div class="col-md-6"><label class="form-label" for="category">Evidence category</label><select class="form-select" name="category" id="category"><option value="grade_12">Grade 12</option><option value="active_tertiary">Active tertiary student</option><option value="prospective_tertiary">Prospective tertiary student</option></select></div><div class="col-md-6"><label class="form-label" for="institution_name">Institution</label><input class="form-control" name="institution_name" id="institution_name"></div><div><button class="btn btn-outline-primary">Save eligibility</button></div></form>@endif
<h2 class="h4 mt-4">Documents</h2><form method="POST" enctype="multipart/form-data" action="{{ route('member.applications.documents.store',$application) }}" class="row g-2">@csrf<div class="col-md-5"><select class="form-select" name="document_type_id">@foreach($documentTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></div><div class="col-md-5"><input class="form-control" type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required></div><div class="col-md-2"><button class="btn btn-outline-primary">Upload</button></div></form>
<form method="POST" action="{{ route('member.applications.submit',$application) }}" class="mt-4">@csrf<label><input type="checkbox" name="declaration" value="1" required> I declare this information is accurate.</label><button class="btn btn-success d-block mt-2">Submit application</button></form>@endif
<h2 class="h4 mt-4">Uploaded documents</h2><ul>@forelse($application->documents as $d)<li><a href="{{ route('documents.download',$d) }}">{{ $d->original_name }}</a> – {{ $d->review_status->value }}</li>@empty<li>No documents uploaded.</li>@endforelse</ul>
@foreach($application->queries as $q)<div class="alert alert-warning"><strong>Administrator query:</strong> {{ $q->message }}@if(!$q->response)<form method="POST" action="{{ route('member.queries.respond',$q) }}">@csrf<textarea class="form-control my-2" name="response" required></textarea><button class="btn btn-warning">Respond</button></form>@else<p>Response: {{ $q->response }}</p>@endif</div>@endforeach
@if(!in_array($application->status->value,['approved','rejected','withdrawn']))<form method="POST" action="{{ route('member.applications.withdraw',$application) }}">@csrf<button class="btn btn-outline-danger">Withdraw application</button></form>@endif</div>@endsection
